### ISSUE TITLE
QH9: Hamiltonians for the same molecule are very similar. 

### ISSUE THREAD

**Issue by AlexanderMath** [divelab/AIRS#10]
The MD trajectories almost don't change (see attached video). The [QHNet](https://arxiv.org/pdf/2306.09549.pdf) baseline gets 70[μHa] MAE. For the first molecule, the MAE between all 60 Hamiltonians is 45[μHa] (see attached image for all pair differences). This might be caused by the small ~2 attosecond time step. In your reply to [reviewer wfG7](https://openreview.net/forum?id=71uRr9N39A&referrer=%5Bthe%20profile%20of%20Shuiwang%20Ji%5D(%2Fprofile%3Fid%3D~Shuiwang_Ji1)) you mention a dataset with larger time steps. Any chance you'll publish this within a few days? 

Please don't hesitate to let me know if I'm misunderstanding something. 

video: https://github.com/divelab/AIRS/assets/8614529/63fd3109-e88f-4b4a-ae4b-eb0a416a87eb
![image](https://github.com/divelab/AIRS/assets/8614529/3954739d-6828-4b99-a167-ea98f815100a)

**Comment by Oceanusity** [comment]
Hello, would you mind sharing the code to generate this figure and video? We plan to release this new dynamic dataset soon, and will test these two.

**Comment by Oceanusity** [comment]
Hello, we have uploaded the new MD datasets. The new MD is conducted with 5 a.u. (https://en.wikipedia.org/wiki/Atomic_units) (~0.12 fs) with 1000 steps. Then, we sample 100 steps evenly (timestep 50 a.u.) to get the QH9Dynamic datasets.  This is conducted in Pyscf 2.3.0. The full dataset will be provided upon request.

**Comment by Oceanusity** [comment]
Hi, I add a [jupyter](OpenDFT/QHBench/QH9/dataset_generation_examples/test_mse_error.ipynb) to show the MAE on the Hamiltonian matrix for the MD trajectory in current dataset. Meanwhile, the dataset generation example code is released [here](https://github.com/divelab/AIRS/tree/main/OpenDFT/QHBench/QH9/dataset_generation_examples). Thanks.
