### ISSUE TITLE
A question about irreps in QHNet

### ISSUE THREAD

**Issue by Mo-Chen21** [divelab/AIRS#15]
Hi. I have a question about irreps in QHNet. In QHNet, it sets `self.hidden_irrep = o3.Irreps(f'{self.hs}x0e + {self.hs}x1o + {self.hs}x2e + {self.hs}x3o + {self.hs}x4e')` and `self.hidden_irrep_base = o3.Irreps(f'{self.hs}x0e + {self.hs}x1e + {self.hs}x2e + {self.hs}x3e + {self.hs}x4e')`. These layers are defined as
https://github.com/divelab/AIRS/blob/b99f68322b14f797c71188c53c63f475d8c5167d/OpenDFT/QHNet/models/QHNet.py#L656-L688
And in forward process:
https://github.com/divelab/AIRS/blob/b99f68322b14f797c71188c53c63f475d8c5167d/OpenDFT/QHNet/models/QHNet.py#L766-L769
The `node_attr` outputs from `e3_gnn_layer` will be the inputs of `e3_gnn_node_layer` and `e3_gnn_node_pair_layer`. I'm confused about why the output irreps of `e3_gnn_layer` is different from the input irreps of `e3_gnn_node_layer` and `e3_gnn_node_pair_layer`?

**Comment by Oceanusity** [comment]
Hello, the difference here is that `self.hidden_irrep` is set to `o3.Irreps(f'{self.hs}x0e + {self.hs}x1o + {self.hs}x2e + {self.hs}x3o + {self.hs}x4e')`.
while `self.hidden_irrep_base` is set to `o3.Irreps(f'{self.hs}x0e + {self.hs}x1e + {self.hs}x2e + {self.hs}x3e + {self.hs}x4e')`.

It is about the parity of the irreps. First of all, it is SE(3)-equivariant no matter it considers the parity or not. Then, when treating all the irreps as even parity, there will be more paths in the Tensor Production and Tensor Expansion operation. For example, `1e, 1e -> 1e` is a valid path while `1o, 1o -> 1o` is not a valid path. 
From previous experiment, when conducting node pair interaction(e3_gnn_node_layer ,  e3_gnn_node_pair_layer) and Expansion, performance can be improved a lot when parity is omitted to include more paths. Therefore, parity is omitted in these two module. While in the node-wise interaction layers, the parity remains as it is faster to include less paths and the performance does not drop.
