### ISSUE TITLE
SMILES of QH9 entries

### ISSUE THREAD

**Issue by Obs01ete** [divelab/AIRS#16]
I have loaded QH9Stable using this code:
https://github.com/divelab/AIRS/blob/main/OpenDFT/QHBench/QH9/datasets.py

I observe the entries are PyG data objects.
```
Data(pos=[5, 3], atoms=[5, 1], diagonal_hamiltonian=[5, 14, 14], non_diagonal_hamiltonian=[20, 14, 14], diagonal_hamiltonian_mask=[5, 14, 14], non_diagonal_hamiltonian_mask=[20, 14, 14], edge_index_full=[2, 20])
```

**How do I get the SMILES of a sample?**
I want to joint the QH9 records with QM9 records by SMILES.
Thanks!

**Comment by Oceanusity** [comment]
Hello, maybe you can try to use rdkit to get the smile strings `smiles = Chem.MolToSmiles(mol)`. There is an example in [MoleculeX](https://github.com/divelab/MoleculeX/blob/molx/molx/dataset/molecule3d.py#L135).

**Comment by Obs01ete** [comment]
> Hello, maybe you can try to use rdkit to get the smile strings `smiles = Chem.MolToSmiles(mol)`. Here are the examples using this function: [Molecule3D dataset in MoleculeX](https://github.com/divelab/MoleculeX/blob/molx/molx/dataset/molecule3d.py#L135) and [QM9 rdkit_functions in e3 diffusion](https://github.com/ehoogeboom/e3_diffusion_for_molecules/blob/fce07d701a2d2340f3522df588832c2c0f7e044a/qm9/rdkit_functions.py#L136).

@Oceanusity thanks for the pointers! I can for sure get SMILES from mol. But how do I get mol from PyG data?
My piece of feedback on QH9 is that adding the corresponding SMILES of a QM9 record to the data object would be enormously helpful.
