### ISSUE TITLE
Request for Dataset Division Files: Following Your Methodology

### ISSUE THREAD

**Issue by TheBestOrNothing-gwh** [divelab/AIRS#18]
I hope this message finds you well.

Your work has been immensely helpful to me, for which I am very grateful. I have developed my own model and wish to test it following the methodology outlined in your paper. However, I could not locate the specific files for the dataset division of Bulk Moduli and Shear Moduli within the Materials Project dataset. Could you kindly provide these files?

Thank you very much for your assistance.

**Comment by YKQ98** [comment]
Sure~ For bulk and shear datasets, we published the datasets at https://figshare.com/projects/Bulk_and_shear_datasets/165430
