### ISSUE TITLE
wrong convention for PySCF format data

### ISSUE THREAD

**Issue by Franklalalala** [divelab/AIRS#19]
[Here](https://github.com/divelab/AIRS/blob/d4304f9fc9d1a05a43bf9154dfce72ff13a80f51/OpenDFT/QHBench/QH9/datasets.py#L26) defined two sets of convention.
However for p obitals, the pyscf has only one set, that is px, py, pz, which corresponds to the magnetic quantum number 1, -1, 0.
To transform it into a spherical hamonic convention, we apply an transform sequence, which is 1, 2, 0.
The def2svp set is correct, though 631G is different. This could cause troubles for new-bees.

**Comment by Oceanusity** [comment]
Thanks for pointing it out. I have fixed it.
