### ISSUE TITLE
A minor issue on the implementation of QHNet

### ISSUE THREAD

**Issue by TongWang-AI4S** [divelab/AIRS#23]
On the line 212, 213, 218, 219 of ori_QHNet_with_bias.py and line 208, 209, 214, 215 of ori_QHNet_with_bias.py, it is written that 
```python
s0 = torch.cat([pre_x[edge_dst][:, self.irrep_in_node.slices()[0]],
                            pre_x[edge_dst][:, self.irrep_in_node.slices()[0]], s0], dim=-1)
```
and
```python
s0 = torch.cat([x[edge_dst][:, self.irrep_in_node.slices()[0]],
                            x[edge_dst][:, self.irrep_in_node.slices()[0]], s0], dim=-1)
```
Maybe they are supposed to be 
```python
s0 = torch.cat([pre_x[edge_dst][:, self.irrep_in_node.slices()[0]],
                            pre_x[edge_src][:, self.irrep_in_node.slices()[0]], s0], dim=-1)
```
and
```python
s0 = torch.cat([x[edge_dst][:, self.irrep_in_node.slices()[0]],
                            x[edge_src][:, self.irrep_in_node.slices()[0]], s0], dim=-1)
```

**Comment by Oceanusity** [comment]
Thank you for pointing that out. It should be the concatenation of the src and dst invariant features. We'll maintain the original file to ensure reproducibility and make this adjustment in a new model file. Thanks again!

**Comment by Oceanusity** [comment]
We fix this issue in this model file https://github.com/divelab/AIRS/blob/main/OpenDFT/QHNet/models/QHNet.py
Thanks.
