### ISSUE TITLE
Track ordering of training data in QHNet

### ISSUE THREAD

**Issue by 19227sh** [divelab/AIRS#24]
The calculation example of QHNet uses the MD-17 data set by default, and when we generate the data set through different DFT software, the orbit arrangement may appear different values, so I would like to know how the program itself specifies the orbit arrangement order

**Comment by Oceanusity** [comment]
Hi, I think the order of orbital is determined by what kind of DFT software you used. The determination of this order may effect the efficiency, some orbitals are related (e.g. m=+1 and m=-1) and  computation cost can be reduced if such relationship is considered during calculation. Therefore, many package will have their own order of orbitals to implement their codes.
