### ISSUE TITLE
PotNet enviroment set up 

### ISSUE THREAD

**Issue by hongshuh** [divelab/AIRS#6]
Hi, I meet an error when running `conda env create -f environment.yml`.

Here is the error message
```
ERROR: Could not find a version that satisfies the requirement torch-cluster==1.6.0+pt112cu116 (from versions: 0.1.1, 0.2.3, 0.2.4, 1.0.1, 1.0.3, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3a1, 1.4.3, 1.4.4, 1.4.5, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.6.0, 1.6.1)

ERROR: No matching distribution found for torch-cluster==1.6.0+pt112cu116

failed

CondaEnvException: Pip failed
```

**Comment by KruskalLin** [comment]
Thanks for the issue. I think this is an installation issue of `torch-geometric`. I rewrote the README and decoupled the `torch-geometric` installation from the yml file. Could you please try it out again? And let me know if you have any questions.

**Comment by hongshuh** [comment]
Thanks for your reply, now I am able to set up the enviroment, but there is another error when run
`python setup.py build_ext --inplace`

```
running build_ext
building 'series' extension
gcc -pthread -B /home/hongshuh/anaconda3/envs/potnet/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/hongshuh/anaconda3/envs/potnet/include -fPIC -O2 -isystem /home/hongshuh/anaconda3/envs/potnet/include -fPIC -I/home/hongshuh/anaconda3/envs/potnet/lib/python3.9/site-packages/numpy/core/include -Igsl/include -I/home/hongshuh/anaconda3/envs/potnet/include/python3.9 -c bessel.c -o build/temp.linux-x86_64-3.9/bessel.o -std=c++11 -I./gsl/include
cc1: warning: command-line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
bessel.c:3:10: fatal error: gsl/gsl_sf_bessel.h: No such file or directory
    3 | #include <gsl/gsl_sf_bessel.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1```

**Comment by KruskalLin** [comment]
Hi, could you please show me your ~/.bashrc about LD_LIBRARY_PATH? I want to see if it is correctly exported.

**Comment by hongshuh** [comment]
> Hi, could you please show me your ~/.bashrc about LD_LIBRARY_PATH?

I was adding `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/hongshuh/PotNet/lib/` to `~/.bashrc`. Did I make a mistake?

**Comment by KruskalLin** [comment]
Should it be like `lib/lib` since `lib` is a gsl subdirectory? I doubt if the path is correct. It works fine in my server, so I need to identify what the cause is first.

**Comment by hongshuh** [comment]
What is your output when run `echo $$LD_LIBRARY_PATH`, I think it is because my path did not set up correctly.

**Comment by hongshuh** [comment]
I create another folder and use it as `TARGET_PATH` to install again and success. Here is my output
```
:/home/hongshuh/PotNet/functions/gsl/lib/
```
 Thanks for your reply!
