### ISSUE TITLE
Trained weights Latent diffusion for protein structure generation

### ISSUE THREAD

**Issue by kilianFatras** [divelab/AIRS#7]
Greetings! 

Thank you for releasing the code of the paper 'A Latent Diffusion Model for Protein Structure Generation'. I was wondering if you have planned to release the trained weights and if so, when would you release them?

**Comment by congffu** [comment]
Hello, thanks for your interest in our paper. The trained weights can be found in this [google drive link](https://drive.google.com/drive/folders/1EvPAIPFmZSq3U8UeGTuOCYSyZRiX5wqN?usp=sharing) .

**Comment by shrimonmuke0202** [comment]
Hi, I  need the preprocessing code to create the training, validation, and test data. Could you please share the amino acid sequences for the training dataset i.e; AlphaFold dataset
